# Requires vars.NAME to be set as a variable.
name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - converted_to_draft
      - ready_for_review
    branches:
      - main
      - dev
      - backport/*.*
    paths:
      - config/**
      - spack.yaml
jobs:
  pr-ci:
    name: CI
    if: >-
      github.event.action != 'closed'
    uses: access-nri/build-cd/.github/workflows/ci.yml@v7
    with:
      model: ${{ vars.NAME }}
      root-sbd: access-esm1p6
      pr: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
      contents: write
      statuses: write
    secrets: inherit
  pr-closed:
    name: Closed
    if: github.event.action == 'closed'
    uses: access-nri/build-cd/.github/workflows/ci-closed.yml@v7
    with:
      root-sbd: access-esm1p6
    secrets: inherit
